# Generated by Django 6.0.3 on 2026-03-08 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oportunidade',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oportunidades', to='customers.cliente'),
        ),
        migrations.AlterField(
            model_name='oportunidade',
            name='etapa',
            field=models.CharField(choices=[('SEM', 'Sem atendimento'), ('ATEND', 'Em atendimento'), ('NEG', 'Negociação'), ('GANHO', 'Fechado'), ('PERD', 'Perdido')], default='SEM', max_length=10),
        ),
        migrations.AlterField(
            model_name='oportunidade',
            name='proximo_contato',
            field=models.DateField(blank=True, null=True),
        ),
    ]
