# Generated by Django 6.0.3 on 2026-03-05 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(choices=[('ENVIADA', 'Mensagem enviada'), ('RECEBIDA', 'Recebida'), ('SEM_RESPOSTA', 'Sem resposta'), ('BLOQUEADO', 'Bloqueado')], max_length=20)),
                ('descricao', models.TextField(blank=True)),
                ('ocorrido_em', models.DateTimeField()),
                ('oportunidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacoes', to='pipeline.oportunidade')),
            ],
        ),
    ]
