# Generated by Django 6.0.3 on 2026-03-08 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interacao',
            name='proximo_contato',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interacao',
            name='ocorrido_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='interacao',
            name='resultado',
            field=models.CharField(choices=[('ENVIADA', 'Mensagem enviada'), ('RECEBIDA', 'Recebida'), ('SEM_RESPOSTA', 'Sem resposta'), ('NEGOCIANDO', 'Negociando'), ('FECHADO', 'Fechado'), ('PERDIDO', 'Perdido'), ('BLOQUEADO', 'Bloqueado')], max_length=20),
        ),
    ]
