# Generated by Django 6.0.3 on 2026-03-05 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('agendada_para', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('FEITA', 'Feita')], default='PENDENTE', max_length=20)),
                ('oportunidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipeline.oportunidade')),
            ],
        ),
    ]
